name: first workflow
on: workflow_dispatch
  jobs:
    first-job:
      runs-on: windows-latest
        steps:
          -name: hi
          run: echo hi
          -name: 2 step
          run: echo bye
          
          
          
